### ISSUE TITLE
CV class: docs? Non-public?

### ISSUE THREAD

**Issue by rpavlik** [adafruit/Adafruit_CircuitPython_EMC2101#11]
https://github.com/adafruit/Adafruit_CircuitPython_EMC2101/blob/3ae2a7c162a4047ecb0ae55db0adef3d78c84c6d/adafruit_emc2101.py#L206

This shows up in the docs, but the actual "constants" being defined don't. Am I correct in thinking this is basically a "fancy Enum" class? Any way to get the constants defined within to show up in docs https://circuitpython.readthedocs.io/projects/emc2101/en/latest/api.html#adafruit_emc2101.CV  short of manually documenting them? Can we just remove this class from the public interface entirely? I don't imagine library users are meant to use it directly.

**Comment by tannewt** [comment]
Ya, I think you can hide it with "_".

**Comment by jposada202020** [comment]
Solved by #15 . Closing. Thanks
